name: Build new

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  organize-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push changes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for proper commit


    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        build-essential \
        cmake \
        wget \
        curl \
        git \
        lsof \
        libcurl4-openssl-dev \
        libssl-dev \
        python3-dev \
        libgomp1 \
        libatomic1 \
        libstdc++6


    - name: Bingo
      run: |
        echo "lets go"
        cd server/new
        pip install -r requirements.txt
        mkdir models
        cd models
        wget -O qwen3.gguf "https://huggingface.co/bartowski/Qwen_Qwen3.5-0.8B-GGUF/resolve/main/Qwen_Qwen3.5-0.8B-Q4_K_M.gguf"
        cd ..
        python server.py
        